function plotReconEye(U,S,V,noReconEyes,avgEye,showPlot,savePlot)

% *************************************************************************
% SUMMARY      : Function to display the reconstructed eye chosen at 
%                random
%
% USAGE        : plotReconEye(U,S,V,noReconEyes,avgEye,showPlot,
%                              savePlot)
%                invoke only in DEBUG mode
%
% ARGUMENTS :
% 
% U            - The upper triangular matrix of the SVD decomposition
% S            - The weights of the SVD decomposition
% V            - The lower triangular matrix of the SVD decomposition
% noReconEyes  - Total number of reconstrution steps to show for one eye
% avgEye       - Mean eye obtained from the full database
% showPlot     - Display the plots generated by this function
% savePlot     - Save the plots generated by this function
%
% *************************************************************************

reconImgNo = 1;
    
if showPlot
    
    fReconEye = figure; axis off;
    set(gcf, 'Name', sprintf('Reconstruction using top %d eigeneyes',...
                              noReconEyes));
    
    eIt    = 1;
    noCols = ceil(sqrt(noReconEyes));
        
    for fIt = 1:noReconEyes          % No. of reconstruction steps to show

        reconVec  = U(:,1:fIt) * S(1:fIt,1:fIt) * V(:,1:fIt)';
        reconEye  = reshape(reconVec(:,reconImgNo), ...
                            size(double(avgEye))) + double(avgEye);

        closeImgPlot(noCols,eIt,reconEye);

        eIt = eIt + 1;

        colormap(gray); axis off;
        drawnow;
    end;        

    % ----------------------------------------------------- Reposition plot

    set(gcf,'paperUnits','centimeters')
    xSize = 12; ySize = 10;
    xLeft = (21-xSize)/2; yTop = (30-ySize)/2;

    set(gcf,'PaperPosition',[xLeft yTop xSize ySize]);
    set(gcf,'Position',[0 500 xSize*50 ySize*50]);   

    if savePlot
        set(gcf,'PaperPositionMode','auto');
        saveas(fReconEye,strcat('results/fig/reconEye.fig'));
        saveas(fReconEye, 'results/eps/reconEye', 'epsc'); 
        saveas(fReconEye,strcat('results/png/reconEye.png'));
        saveas(fReconEye,strcat('results/pdf/reconEye.pdf'));
    end
end