function plotEigenEyes(U,noEEyes,avgEye,showPlot,savePlot)

% *************************************************************************
% SUMMARY   : Function to display eigenEyes (eEyes)
%
% USAGE     : plotEigenEyes(U,noEEyes,avgEye,showPlot,savePlot)
%             invoke only in DEBUG mode
%
% ARGUMENTS :
% 
% U         - The upper triangular matrix from the SVD decomposition
% noEEyes   - Number of eigenEyes to plot
% avgEye    - Avg. eye of the training eyes
% showPlot  - Display the plots generated by this function
% savePlot  - Save the plots generated by this function
%
% *************************************************************************

if showPlot
    
    eigenEyes = figure; axis off;
    set(gcf, 'Name', sprintf('Top %d Eigeneyes',noEEyes));
    
    noCols = ceil(sqrt(noEEyes));

    for eIt = 1:noEEyes
        closeImgPlot(noCols,eIt,reshape(U(:,eIt), size(avgEye)));
    end

    colormap(gray);                                  % Black-white colormap

    if savePlot
        set(gcf,'PaperPositionMode','auto');
        saveas(eigenEyes,strcat('results/fig/eigenEyes.fig'));
        saveas(eigenEyes, 'results/eps/eigenEyes', 'epsc'); 
        saveas(eigenEyes,strcat('results/png/eigenEyes.png'));
        saveas(eigenEyes,strcat('results/pdf/eigenEyes.pdf'));
    end
end